### ISSUE TITLE
Float numbers do not work

### ISSUE THREAD

**Issue by beinoriusju** [om06/google-currency#1]
Thats for very cool lib! Unfortunately run into issue converting FLOATS

**Problem description**

Using this code does return an invalid computation.

```
from google_currency import convert

convert('EUR', 'USD', 1.5)
```
**Expected behavior**

Returns 1.5 EUR converted to USD (1.66 as of today)

`{"amount": "1.66", "converted": true, "to": "USD", "from": "EUR"}`

**Actual behavior**

Returns

`{"amount": "0.0", "converted": true, "to": "USD", "from": "EUR"}`

I'm using Python 3.5, google-currency 1.0.3

**Comment by om06** [comment]
As I can check, I am unable to find any issue regarding the same. It is working perfectly fine, so closing this issue. Kindly let me know if you run into any other issue, I will be happy to help. :-)

![image](https://user-images.githubusercontent.com/22866611/70343765-1aa22000-187e-11ea-8e10-da0186ec11ef.png)

P.S: I am using python 3.6 and google-currency 1.0.3

**Comment by beinoriusju** [comment]
There is no official Python3.6 packages for my Debian machine, but I doubt it has any effects on wrong output I get.

Can you give me instruction on building package and testing myself? I believe it's Google that displays different results for users located in different countries and would like to investigate contents returned. I would report back on my findings.

![image](https://user-images.githubusercontent.com/24639014/70525566-5542db80-1b50-11ea-98a5-28ba7c95307b.png)

**Comment by om06** [comment]
Please upgrade the google-currency package, I've made some changes. Hope
that will solve the problem.

**Comment by beinoriusju** [comment]
Thanks!

I see you've updated application to point Google IP address. Unfortunately it did not solve my problem. Having cloned you repository files I've found Google automatically translating currency results (currency codes included) to Lithuanian language.

I've found a solution and proposed a change.

Thanks for the library.

I'm hoping to release something useful soon too.

**Comment by om06** [comment]
Great, Good Luck 🙂

**Comment by om06** [comment]
Great, Thanks for the solution... And Good luck for whatever you are releasing 🙂
