### ISSUE TITLE
Returns 'true' instead of 'True'

### ISSUE THREAD

**Issue by ghost** [om06/google-currency#4]
After calling the convert function, it returns a json response with value 'true' instead of 'True', so python treats 'true' as a variable when I want to convert the converted currency string to a dictionary using eval() function.
![image](https://user-images.githubusercontent.com/22393832/104124830-9319c100-535b-11eb-9a3b-f9353b5c9468.png)

**Comment by om06** [comment]
Do not use eval function to parse the result. This returns Json and you
should use json.loads() to convert it in dictionary.
